### ISSUE TITLE
Outlook Tool Download Error

### ISSUE THREAD

**Issue by wilsonmarissa** [rpaugh/Alteryx-Outlook-Tools#3]
I get the following error when I try to install the Outlook tool for Alteryx. I have both versions 10.6 and 11.5 on my machine.

![image](https://user-images.githubusercontent.com/35933937/35528625-7166b334-04fc-11e8-94f8-2ce58f28b013.png)

**Comment by perla08o** [comment]
I have this same issue trying to install in 10.6

**Comment by rpaugh** [comment]
I just published a version of the tool that works with 10.6.  You can download it [here](https://gallery.alteryx.com/#!app/Outlook-Tools-Install--10-6-/5a74751cf499c72598ba0e33).  I seem to be having trouble placing it in the public gallery at the moment so you may have to login to download it.

**Comment by rpaugh** [comment]
The installation workflow was created in an newer version of Alteryx though so you may have to download the installer directly [here](https://drive.google.com/open?id=0B11L6XXkpz_YNGFuMGlFQTBIVEE).

**Comment by pgensler** [comment]
Has this been fixed? I tried to download this tool from the Alteryx Gallery, and I receive the following error:
`{"data":null,"exceptionName":"NotFoundException","innerExceptionMessage":"","message":"Temporary authentication token not found."}`

**Comment by pgensler** [comment]
@rpaugh In the interim, it might be best to post that link to download the tool on the `readme` page untill it is fixed in the gallery.

**Comment by rpaugh** [comment]
Hello all,

The problem here is that every time I implement an update and refresh the executable file in the workflow, Alteryx updates the workflow to the current version.  You can either open the XML for the workflow after you download it, change the version to your version, and then open it; or download the executable directly.  Per @pgensler 's suggestion, I've updated the Readme file to include the direct link to the installer executable.

Rick
